"""
statistics.py — Phase 6 execution telemetry.

RECTIFIED: Phase6Stats (frozen dataclass) replaced with:
    - Phase6StatsCollector: mutable accumulator (no frozen schema issues)
    - DiscoveryReport: serializable report object produced by finalize()

This prevents the "frozen schema becomes annoying" problem while keeping
the clean separation between collection and reporting.

Rules:
    ✅ Never influences execution
    ✅ DiscoveryReport is JSON-serializable
    ✅ New metrics can be added to StatsCollector without schema freeze pain
    ❌ Never modifies any pipeline object
"""

from __future__ import annotations

import json
import time
from dataclasses import asdict, dataclass

import structlog

from smriti.core.models import RelationshipType

logger = structlog.get_logger(__name__)


@dataclass
class DiscoveryReport:
    """
    Serializable report of Phase 6 execution.

    Generated by Phase6StatsCollector.finalize().
    This is what gets written to manifests and logs.
    """

    total_embedded_claims: int
    total_candidate_pairs: int
    validated_candidates: int
    rejected_candidates: int
    nli_calls: int
    relationships_produced: int
    contradictions: int
    supports: int
    refinements: int
    neutrals: int
    unknowns: int
    rejected_relationships: int
    total_runtime_seconds: float
    retrieval_latency_seconds: float
    nli_latency_seconds: float
    calibration_applied_count: int
    conflicts_resolved: int
    cache_hit_rate: float
    # Histogram of calibrated confidence scores (10 buckets, 0.0–1.0)
    confidence_histogram: dict[str, int]
    # Rejection reasons breakdown
    rejection_breakdown: dict[str, int]
    # RECTIFIED (P1-J, "FINAL REVIEW" round): true iff ResourceGovernor
    # truncated the candidate list this run (resource_governance.
    # cancel_on_limit was false and max_pairs was exceeded). A consumer
    # of this report -- especially an evaluation script -- must treat
    # any headline recall/precision number from a run with this set true
    # as invalid, not silently smaller.
    evaluation_truncated: bool = False
    # RECTIFIED (P1-I, "FINAL REVIEW" round): NLI batch-failure
    # accounting, carried from NLIEvidenceGenerator.last_run_stats so a
    # failed-and-skipped batch is visible in the persisted report, not
    # just in a log line.
    nli_candidates_attempted: int = 0
    nli_candidates_scored: int = 0
    nli_batch_failures: int = 0
    nli_retries: int = 0

    def to_dict(self) -> dict:
        return asdict(self)

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent)


class Phase6StatsCollector:
    """
    Mutable accumulator for Phase 6 statistics.

    Add new metrics here without breaking any frozen schema.
    Call finalize() to produce a DiscoveryReport.
    """

    def __init__(self) -> None:
        self._total_embedded = 0
        self._total_candidates = 0
        self._validated_candidates = 0
        self._rejected_candidates = 0
        self._nli_calls = 0
        self._relationships = 0
        self._by_type: dict[str, int] = {t.value: 0 for t in RelationshipType}
        self._rejected_relationships = 0
        self._calibration_applied = 0
        self._conflicts_resolved = 0
        self._cache_hit_rate = 0.0
        self._rejection_breakdown: dict[str, int] = {}
        self._confidence_buckets: dict[str, int] = {
            f"{i/10:.1f}-{(i+1)/10:.1f}": 0 for i in range(10)
        }
        self._start_time = time.monotonic()
        self._retrieval_start: float | None = None
        self._retrieval_end: float | None = None
        self._nli_start: float | None = None
        self._nli_end: float | None = None
        self._evaluation_truncated = False
        self._nli_run_stats: dict[str, int] = {}

    def record_embedded_claims(self, count: int) -> None:
        self._total_embedded = count

    def record_candidate_start(self) -> None:
        self._retrieval_start = time.monotonic()

    def record_candidate_end(self, total: int, validated: int, rejected: int) -> None:
        self._retrieval_end = time.monotonic()
        self._total_candidates = total
        self._validated_candidates = validated
        self._rejected_candidates = rejected

    def record_nli_start(self) -> None:
        self._nli_start = time.monotonic()

    def record_nli_end(self, calls: int) -> None:
        self._nli_end = time.monotonic()
        self._nli_calls = calls

    def record_relationship(
        self,
        rel_type: RelationshipType,
        calibrated_confidence: float,
        calibration_applied: bool,
    ) -> None:
        self._relationships += 1
        self._by_type[rel_type.value] = self._by_type.get(rel_type.value, 0) + 1
        if calibration_applied:
            self._calibration_applied += 1
        # Bucket the confidence score
        bucket_idx = min(int(calibrated_confidence * 10), 9)
        bucket_key = f"{bucket_idx/10:.1f}-{(bucket_idx+1)/10:.1f}"
        self._confidence_buckets[bucket_key] = self._confidence_buckets.get(bucket_key, 0) + 1

    def record_rejected_relationship(self, reason: str = "unknown") -> None:
        self._rejected_relationships += 1
        self._rejection_breakdown[reason] = self._rejection_breakdown.get(reason, 0) + 1

    def record_conflict_resolved(self) -> None:
        self._conflicts_resolved += 1

    def record_cache_hit_rate(self, rate: float) -> None:
        self._cache_hit_rate = rate

    def record_truncation(self, truncated: bool) -> None:
        """RECTIFIED (P1-J): carry ResourceGovernor.evaluation_truncated into the report."""
        self._evaluation_truncated = self._evaluation_truncated or truncated

    def record_nli_run_stats(self, stats: dict[str, int]) -> None:
        """RECTIFIED (P1-I): carry NLIEvidenceGenerator.last_run_stats into the report."""
        self._nli_run_stats = stats

    def finalize(self) -> DiscoveryReport:
        """Produce the final DiscoveryReport."""
        elapsed = time.monotonic() - self._start_time
        retrieval_latency = (
            (self._retrieval_end - self._retrieval_start)
            if self._retrieval_start and self._retrieval_end
            else 0.0
        )
        nli_latency = (
            (self._nli_end - self._nli_start) if self._nli_start and self._nli_end else 0.0
        )

        return DiscoveryReport(
            total_embedded_claims=self._total_embedded,
            total_candidate_pairs=self._total_candidates,
            validated_candidates=self._validated_candidates,
            rejected_candidates=self._rejected_candidates,
            nli_calls=self._nli_calls,
            relationships_produced=self._relationships,
            contradictions=self._by_type.get("contradicts", 0),
            supports=self._by_type.get("supports", 0),
            refinements=self._by_type.get("refines", 0),
            neutrals=self._by_type.get("neutral", 0),
            unknowns=self._by_type.get("unknown", 0),
            rejected_relationships=self._rejected_relationships,
            total_runtime_seconds=elapsed,
            retrieval_latency_seconds=retrieval_latency,
            nli_latency_seconds=nli_latency,
            calibration_applied_count=self._calibration_applied,
            conflicts_resolved=self._conflicts_resolved,
            cache_hit_rate=self._cache_hit_rate,
            confidence_histogram=dict(self._confidence_buckets),
            rejection_breakdown=dict(self._rejection_breakdown),
            evaluation_truncated=self._evaluation_truncated,
            nli_candidates_attempted=self._nli_run_stats.get("n_candidates_attempted", 0),
            nli_candidates_scored=self._nli_run_stats.get("n_candidates_scored", 0),
            nli_batch_failures=self._nli_run_stats.get("n_batch_failures", 0),
            nli_retries=self._nli_run_stats.get("n_retries", 0),
        )
