"""
reporting/exporter.py — Phase 12 CertificationReport exporter (rectified).

RECTIFIED:
    - Shows gate decisions (not just overall level)
    - Shows ArtifactReadinessLevel (not boolean)
    - Shows ResearchClaim.research_question and null_hypothesis
"""

from __future__ import annotations

from pathlib import Path

from smriti.core.models import CertificationReport


def export_markdown_summary(report: CertificationReport) -> str:
    level = report.certification_level
    lines = [
        "# SMRITI Certification Report",
        "",
        f"**Report ID:** `{report.report_id}`  ",
        f"**Run ID:** `{report.run_id}`  ",
        f"**Generated:** {report.timestamp_iso}  ",
        f"**Schema Version:** {report.schema_version}  ",
        "",
        "---",
        "",
        "## Certification Status",
        "",
        "| Dimension | Value |",
        "|-----------|-------|",
        f"| **Certification Level** | **{level.value} — {level.name}** |",
        f"| Engineering Confidence Index (ECI) | {report.engineering_confidence_index:.1f}/100 |",
        f"| Research Evidence Coverage | {report.research_evidence_coverage_index:.1f}/100 |",
        f"| Overall Confidence Index | {report.overall_confidence_index:.1f}/100 *(informational only)* |",
        "",
        f"**Rationale:** {report.certification_rationale}",
        "",
        "---",
        "",
        "## Certification Gate Results (RECTIFIED: gate-based, not score-based)",
        "",
        "| Gate | Name | Decision | Metric | Required | Notes |",
        "|------|------|----------|--------|----------|-------|",
    ]
    for g in report.gate_results:
        decision_icon = "✅" if g.decision.value == "pass" else "❌"
        observed = f"{g.metric_observed:.1f}" if g.metric_observed is not None else "—"
        required = f"{g.metric_required:.1f}" if g.metric_required is not None else "—"
        notes = g.blocking_reason or g.rationale[:50]
        lines.append(
            f"| {g.gate_number} | {g.gate_name} | {decision_icon} {g.decision.value} | {observed} | {required} | {notes} |"
        )

    lines += [
        "",
        "---",
        "",
        "## Engineering Confidence (Part 2)",
        "",
        "| Dimension | Score |",
        "|-----------|-------|",
        f"| Architecture | {report.engineering_confidence.architecture_confidence:.1f} |",
        f"| Runtime | {report.engineering_confidence.runtime_confidence:.1f} |",
        f"| Infrastructure | {report.engineering_confidence.infrastructure_confidence:.1f} |",
        f"| Observability | {report.engineering_confidence.observability_confidence:.1f} |",
        f"| Governance | {report.engineering_confidence.governance_confidence:.1f} |",
        f"| Integration | {report.engineering_confidence.integration_confidence:.1f} |",
        f"| Compliance | {report.engineering_confidence.compliance_confidence:.1f} |",
        f"| **Overall ECI** | **{report.engineering_confidence.overall_confidence:.1f}** |",
        "",
        "---",
        "",
        "## Research Claims Matrix (RECTIFIED: enriched scientific objects)",
        "",
        "| Claim | Statement | Grade | Supported | Research Question |",
        "|-------|-----------|-------|-----------|-------------------|",
    ]
    for claim in report.research_claims:
        stmt_short = claim.statement[:50] + ("..." if len(claim.statement) > 50 else "")
        rq_short = claim.research_question[:50] + (
            "..." if len(claim.research_question) > 50 else ""
        )
        icon = "✅" if claim.is_supported else "❌"
        lines.append(
            f"| {claim.claim_id} | {stmt_short} | {claim.evidence_grade.value} | {icon} | {rq_short} |"
        )

    lines += [
        "",
        "---",
        "",
        "## Artifact Readiness (RECTIFIED: ordinal, not binary)",
        "",
        f"**Readiness Level:** {report.artifact_readiness.readiness_level.value}",
        f"**Revision Notes:** {report.artifact_readiness.revision_notes}",
        "",
        "| Status | Criteria |",
        "|--------|----------|",
        f"| ✅ Met | {', '.join(report.artifact_readiness.criteria_met) or 'none'} |",
        f"| ⚠️ Partial | {', '.join(report.artifact_readiness.criteria_partial) or 'none'} |",
        f"| ❌ Missing | {', '.join(report.artifact_readiness.criteria_missing) or 'none'} |",
        "",
        "---",
        "",
        "## Threats to Validity (Part 4)",
        "",
        "| ID | Category | Residual Risk |",
        "|----|----------|---------------|",
    ]
    for threat in report.threats_to_validity:
        lines.append(f"| {threat.threat_id} | {threat.category} | {threat.residual_risk} |")

    lines += [
        "",
        "---",
        "",
        f"*Generated by SMRITI Phase 12 Scientific Validation Framework v{report.schema_version}*",
    ]
    return "\n".join(lines)


def export_text_summary(report: CertificationReport) -> str:
    level = report.certification_level
    supported = sum(1 for c in report.research_claims if c.is_supported)
    total_claims = len(report.research_claims)
    gates_passed = sum(1 for g in report.gate_results if g.decision.value == "pass")

    lines = [
        "=" * 70,
        "SMRITI — PHASE 12 CERTIFICATION REPORT",
        "=" * 70,
        f"  Run ID:               {report.run_id}",
        f"  Report ID:            {report.report_id}",
        f"  Generated:            {report.timestamp_iso}",
        f"  Schema Version:       {report.schema_version}",
        "",
        "  CERTIFICATION LEVEL",
        "  " + "─" * 60,
        f"  Level {level.value}: {level.name}",
        "",
        "  GATE RESULTS (gate-based, not score-based)",
        "  " + "─" * 60,
    ]
    for g in report.gate_results:
        icon = "✅ PASS" if g.decision.value == "pass" else "❌ BLOCK"
        lines.append(f"  Gate {g.gate_number}: {g.gate_name:28s} {icon}")
    lines.append(f"  Gates Passed: {gates_passed}/{len(report.gate_results)}")
    lines += [
        "",
        "  CONFIDENCE INDICES (informational)",
        "  " + "─" * 60,
        f"  Engineering Confidence Index (ECI): {report.engineering_confidence_index:.1f}/100",
        f"  Research Evidence Coverage:         {report.research_evidence_coverage_index:.1f}/100",
        "",
        "  VERIFICATION SUMMARY",
        "  " + "─" * 60,
        f"  Rules Passed: {report.total_rules_passed} / "
        f"{report.total_rules_passed + report.total_rules_failed}",
        f"  Experiments:  {len(report.experiment_results)} executed",
        f"  Research Claims: {supported}/{total_claims} supported",
        "",
        "  ARTIFACT READINESS (ordinal, not binary)",
        "  " + "─" * 60,
        f"  Level: {report.artifact_readiness.readiness_level.value.upper()}",
        f"  Notes: {report.artifact_readiness.revision_notes}",
        "",
        "  RATIONALE",
        "  " + "─" * 60,
    ]
    for part in report.certification_rationale.split(" | "):
        lines.append(f"  {part}")
    lines += ["", "=" * 70]
    return "\n".join(lines)


def write_certification_artifacts(report: CertificationReport, output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "certification_summary.md").write_text(
        export_markdown_summary(report), encoding="utf-8"
    )
    (output_dir / "certification_summary.txt").write_text(
        export_text_summary(report), encoding="utf-8"
    )
